#!/usr/bin/python

array = ['-a(--all)','-A(--almost-all)','--author','-b(--escape)','-B(--ignore-backups)','-C','-D(--dired)','-f','-F(--classify)','-g','-G(--no-group)','-h(--human-readable)','--si','-H(--dereference-command-line)','-i(--inode)','-k','-l','-L(--dereference)','-m','-n(--numeric-uid-gid)','-N(--literal)','-o','-p','-q(--hide-control-chars)','-Q(--quote-name)','-r(--reverse)','-R(--recursive)','-s(--size)','-S','-t','-T','-u','-U','-v','-w','-x','-X','-Z(--context)','-1', '--help', '--version']

import sys
from PyQt4.QtGui import *
from PyQt4.QtCore import *

class Window(QWidget):
    def __init__(self):
        QWidget.__init__(self)
	
	self.button = QPushButton('execute', self)
	self.button.clicked.connect(self.execute)
        layout1 = QVBoxLayout()
	layout1.addWidget(self.button)
        self.checks = []
        for i in xrange(30):
            c = QCheckBox(array[i])
            layout1.addWidget(c)
            self.checks.append(c)
        self.setLayout(layout1)

    def execute(self):
 	print ('Hello World')

if __name__ == '__main__':
    app = QApplication(sys.argv)

    w = Window()
    w.show()

    app.exec_()


